### ISSUE TITLE
Пример запроса

### ISSUE THREAD

**Issue by bxiit** [kostylevv/filmorate#3]
Вижу всё отлично но пример запроса "Получение самых рейтинговых (залайканных) фильмов" кажется не логичным

![Снимок экрана 2024-06-21 145557](https://github.com/kostylevv/filmorate/assets/158191586/c446803b-c35c-40d6-ac3b-110cb4f0b374)

**Comment by kostylevv** [comment]
Согласен) спасибо! поправил
